on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore UsersWebApiMoq16_03_2026.sln

    - name: Build
      run: dotnet build UsersWebApiMoq16_03_2026.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test UsersWebApiMoq16_03_2026.sln --no-build
